### ISSUE TITLE
lzma missing

### ISSUE THREAD

**Issue by ilia-khaustov** [mhbashari/Install-Python3.4-on-Ubuntu-16.04#1]
To include lzma support I suggest adding `sudo apt install lzma lzma-dev liblzma-dev` to the Install Required Packages section.

**Comment by mhbashari** [comment]
Thank you ...
but..
What is the advantages of that?

**Comment by ilia-khaustov** [comment]
I have tried to install Python 3.4.5 following your tutorial and couldn't
import lzma module because _lzma was missing. lzma is a core module and
should be available by default. Installing listed packages fixed my issue.

**Comment by mhbashari** [comment]
I append that line in the requirement packages section
Thanks a lot !
